language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
  - "pip install coveralls"
script: coverage run --source=tortilla test_tortilla.py
after_success: coveralls